### ISSUE TITLE
PLAYER_STOP doesn't stop and end the playback

### ISSUE THREAD

**Issue by alexander-heimbuch** [podlove/podlove-ui#942]

**Comment by DominicWrege** [comment]
Should I provide some example code for reproducing this kind of behavior?

**Comment by alexander-heimbuch** [comment]
The expected behaviour would be nice. Right now I'm planning to trigger the native stop event. This will move the playtime to the end.

**Comment by DominicWrege** [comment]
https://github.com/DominicWrege/podlove-webplayer-stop-bug

The expected behaviour would be that the player basically stops what it is currently playing.

**Comment by alexander-heimbuch** [comment]
Hmm ok did you try to `PLAYER_REQUEST_PAUSE`?

**Comment by DominicWrege** [comment]
Yes but this is only a temporary solution.

**Comment by alexander-heimbuch** [comment]
Why would it be temporary? I did some research and there isn't a native stop event in the html5 audio stack. So `pause` should be fine.

**Comment by DominicWrege** [comment]
>  I did some research and there isn't a native stop event in the html5 audio stack

Good Point.

I its only temporary because I don't  want to pause the playback. 

It should stop/pause the playback and sets the current playback time to 0 or the beginning.

https://github.com/podlove/podlove-ui/blob/1e985675ff64c6016f5b8f9b63dc0b3e4d76767d/packages/player/actions/types.js#L141

So than I don't understand the purpose that line.

**Comment by DominicWrege** [comment]
The new [Media Session API](https://w3c.github.io/mediasession/#actions-model) has defined a stop behaviour.

> stop: the action’s intent is to stop the playback and clear the state if appropriate.

That behaviour I  would expect to happen.
