### ISSUE TITLE
Integrating Podlove player into Vue3 application

### ISSUE THREAD

**Issue by mpiniarski** [podlove/podlove-ui#980]
Hello,
I would like to integrate the player into a standalone Vue3 application as described here:
https://docs.podlove.org/podlove-web-player/v5/templating/getting-started#custom-templating

I'm not able to use the components though. I can see they are defined in a codebase here:
https://github.com/podlove/podlove-ui/tree/development/apps/player/src/components
but the npm module (https://www.npmjs.com/package/@podlove/player) does not seem to contain them.

Can you provide me with information on how to properly integrate the Podlove Player to be able to reuse its components and build its own template in the Vue application?

**Comment by alexander-heimbuch** [comment]
Hey,
there are a couple of things you should take into account if you want to integrate the player into a Vue3 application:

1. The player itself creates state bound components by composing the application state, side effects and ui components. Therefore a simple integration isn’t that easy since the player needs to be hooked on to the state management. Still all of the functional parts are available as separate npm packages. This simple example illustrates how a composition in an app would look like: https://codesandbox.io/s/player-example-73egi
2. Right now the Player is written in Vue2 I’m currently working on an upgrade and already have a working draft but need to stabilize unit and integration tests. So reusing Vue2 components in a Vue3 application might work from case to case but isn’t guaranteed.
3. There is a way of using the `web-player` package to integrate the player sandboxed with an iframe to your application. Unfortunately that comes with the cost that you can’t share the application runtime which has downsides to the bundling size/shipped code. I did that for VuePress and there is also a `player-react` npm package out there that does the same thing. If you are interested I could share the code.

In case you need help with the integration don’t hesitate to reach out. I’m always curious about integration requirements.

**Comment by mpiniarski** [comment]
Thanks for the response :D
I'll go with implementing using web-player. I would prefer to avoid using iframe and just use components with state management, but as I can see it's not easy to achieve.
Here is a code sample of how it works in my case:

```
<script lang="tsx">

import ...

// loading source from cdn
const scriptElement = document.createElement('script');
scriptElement.async = false;
scriptElement.src = "https://cdn.podlove.org/web-player/5.x/embed.js";
document.head.appendChild(scriptElement);


const config: PodlovePlayerConfig = {
  ...
};


export default defineComponent({
  name: 'Player',
  components: {Loader},
  props: {
    ...
  },
  setup(props, context) {
    const episodeConfig: PodlovePlayerEpisode = {
      ... // based on props
    };

    function loadPodlovePlayer() {
      (window as any).podlovePlayer('#player', episodeConfig, config)
    }

    // load right away if podlovePlayer is available, otherwise wait for it to load
    (window as any).podlovePlayer != null
      ? loadPodlovePlayer()
      : scriptElement.onload = () => {
        loadPodlovePlayer()
      }

    return () => {
      return <div style="height: 250px;position: relative;">
        <Loader style="position: absolute; left: 50%; top: 50%; z-index: -1;"/>
        <div class="player" id="player" style="z-index: 2;" v-html={`
          <root class="root" style="
              display: flex;
              flex-direction: row;
              align-items: flex-start;
              width: 100%;
          ">
              // ... all components here e.g. <progress-bar></progress-bar>
         </root>
      `}/>
      </div>;
    }
  }
});

</script>
```

There are a couple of issues:
- vue is declarative while loading podlove player is imperative, so it's impossible to dynamically change the content inside of the player e.g. reload player with another podcast episode.
- all the styles are inline, which has some limitations
- styles are defined in ts, so it's harder to reuse common code defined in scss (in my project).

I'll work on the issues. What do you think about such a solution?

@alexander-heimbuch I would like to take a look at `player-react` implementation, can you share the code?

**Comment by alexander-heimbuch** [comment]
Here is an example with reactive props:

```vue
<template>
  <div class="player" :id="id" :data-variant="variant" :data-template="template"><slot></slot></div>
</template>

<script>
  export default {
    name: 'PodloveWebPlayer',
    props: {
      episode: {
        type: [String, Object],
        default: () => null
      },
      config: {
        type: [String, Object],
        default: () => null
      },
      id: {
        type: String
      },
      variant: {
        type: String,
        default: null,
        validator: (val) => ['xl', 'l', 'm'].includes(val)
      },
      template: {
        type: String,
        default: null
      }
    },
    async mounted() {
      const config = await fetch(this.config).then(response => response.json())
      const base = this.$site.base
      window.podlovePlayer(this.$el, this.episode, { ...config, base }).then(store => {
        this.$emit('ready', store)
        return store
      }).then(window.registerExternalEvents(this.id))
    }
  }
</script>

<style lang="scss" scoped>
  .player {
    margin-bottom: 1.5em;
  }
</style>
```

You can use it like that:
```
<podlove-web-player episode="fixtures/episode.json" config="fixtures/config.json">
  <root v-pre style="max-width:950px;min-width:260px;" class="p-4 flex justify-center rounded">
    <play-button></play-button>
  </root>
</podlove-web-player>
```

**Comment by nodomain** [comment]
Thank you. This is the result :) 
https://siemens.fm/public/podcasts/412400e8e7aee1b0cf4d0b960764e2b42d7c183743d14d0a840566021d025cc9/details

**Comment by alexander-heimbuch** [comment]
Good stuff 👍
